# Generated by Django 4.2.9 on 2024-03-06 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Magura', 'Magura'), ('Gopalganj', 'Gopalganj'), ('Barishal', 'Barishal')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SourceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Kumilla', 'Kumilla'), ('Rajsahi', 'Rajsahi')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField(default=models.PositiveIntegerField())),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='train.destinationstation')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='train.sourcestation')),
            ],
        ),
    ]
